service: FindAMoo 

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage} 
  region: us-west-1
  environment: 
    NODE_ENV: production 

functions:
  app:
    handler: app.server
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true 